server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_project_db
    username: postgres
    password: behdad2012


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update